### ISSUE TITLE
Products not showing full descriptions

### ISSUE THREAD

**Issue by npearce-kpmg** [kpmg-agile/ca-pqvp#329]
Newlines and commas in descriptions are truncating or incorrectly concatenating descriptions.
Also, trademark symbols are not translated

**Comment by npearce-kpmg** [comment]
Correcting now

**Comment by robertlevy** [comment]
putting this in backlog.  i know you've got a fix but the impact here is unlikely to change how we are judged so we're going to err on the side of keeping code frozen for the final hour we have before deadline
